[tool.ruff]
# Configuración de línea máxima
line-length = 88

# Configuración de formateo
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

# Configuración del linter
[tool.ruff.lint]
# Habilitar reglas de pycodestyle
select = ["E", "F", "I", "N", "W", "B", "C4", "UP", "PL", "RUF"]
ignore = []

# Configuración de importaciones
[tool.ruff.lint.isort]
known-first-party = ["app"] 